In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("data/cached_df.csv")

TypeError: read_csv() got an unexpected keyword argument 'fromat'

In [5]:
df

,text,tweet_id,created_at
0,Audi RS E-Tron GT 2022 ? I’m tempted @Audi htt...,1416060510676656130,2021-07-16T15:41:49
1,Congratulations @audi for excluding the market...,1402539175958781950,2021-06-09T08:12:52
2,Did @Audi Just Hint At The Return Of The Manua...,1237481742291746820,2020-03-10T20:53:33
3,What's the name of this @Audi @AudiOfficial ht...,1238551306404605950,2020-03-13T19:43:37
4,How Wind Shaped 100 Years Of Car Design https:...,1576920006092197890,2022-10-03T13:00:01
...,...,...,...
210,"Former @Audi CEO Rupert Stadler, on trial over...",1349028793302843390,2021-01-12T16:21:42
211,Audi unveils the new Audi Skysphere concept an...,1426962887789187070,2021-08-15T17:43:58
212,Audi R8 V10 INSANE** Launch Control #Shorts ht...,1400423086315511810,2021-06-03T12:04:17
213,I’m still waiting for @Audi to release the RSQ...,1566850652688498690,2022-09-05T18:08
214,WE ARE LEVEL! Patryk Klimala from the spot!!\r...,1561118553733996540,2022-08-20T22:30:42

In [11]:
pd.to_datetime(df['created_at'],format="ISO8601")

0     2021-07-16 15:41:49
1     2021-06-09 08:12:52
2     2020-03-10 20:53:33
3     2020-03-13 19:43:37
4     2022-10-03 13:00:01
              ...
210   2021-01-12 16:21:42
211   2021-08-15 17:43:58
212   2021-06-03 12:04:17
213   2022-09-05 18:08:00
214   2022-08-20 22:30:42
Name: created_at, Length: 215, dtype: datetime64[ns]

In [12]:
dictionary = pd.read_csv("data/cached_dictionary.csv")

In [16]:
drives_list = dictionary.columns.tolist()
drives_list.remove('term')
drives_list

['price_pos',
 'price_neg',
 'squality_pos',
 'squality_neg',
 'goodsq_pos',
 'goodsq_neg',
 'cool_pos',
 'cool_neg',
 'exciting_pos',
 'exciting_neg',
 'innov_pos',
 'innov_neg',
 'socresp_pos',
 'socresp_neg',
 'comm_pos',
 'comm_neg',
 'friendly_pos',
 'friendly_neg',
 'personalrel_pos',
 'personalrel_neg',
 'trust_pos',
 'trust_neg']

In [14]:
dictionary

,term,price_pos,price_neg,squality_pos,squality_neg,goodsq_pos,goodsq_neg,cool_pos,cool_neg,exciting_pos,...,socresp_pos,socresp_neg,comm_pos,comm_neg,friendly_pos,friendly_neg,personalrel_pos,personalrel_neg,trust_pos,trust_neg
0,cheap,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,afford,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,inexpen,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,deal,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,low,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,shadi,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
181,untrustwo,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
182,deceit,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
183,decept,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
184,lie,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [22]:
pd.read_excel("data/weekly_gran.xlsx").columns

C:\Users\paolo\miniconda3\envs\streamlit-apps\Lib\site-packages\openpyxl\styles\stylesheet.py:241: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Index(['Total_Tweets', 'created_at', 'Price_Net', 'Squality_Net',
       'Gquality_Net', 'Value Driver', 'Cool_Net', 'Innovative_Net',
       'Exciting_Net', 'SocResp_Net', 'Brand Driver', 'Community_Net',
       'Friendly_Net', 'PersonalRel_Net', 'Trustworthy_Net',
       'Relationship Driver', 'Brand Reputation'],
      dtype='object')

In [23]:
pd.read_csv("trash/check_output.csv").columns

Index(['year', 'quarter', 'total_tweets', 'price_pos', 'price_neg',
       'squality_pos', 'squality_neg', 'goodsq_pos', 'goodsq_neg', 'cool_pos',
       'cool_neg', 'exciting_pos', 'exciting_neg', 'innov_pos', 'innov_neg',
       'socresp_pos', 'socresp_neg', 'comm_pos', 'comm_neg', 'friendly_pos',
       'friendly_neg', 'personalrel_pos', 'personalrel_neg', 'trust_pos',
       'trust_neg', 'Price_net', 'Gquality_net', 'Goodsq_net', 'Value_Driver',
       'Cool_net', 'Innovative_net', 'Exciting_net', 'SocResp_net',
       'Brand_Driver', 'Community_net', 'Friendly_net', 'PersonalRel_net',
       'Trustworthy_net', 'Relationship_Driver', 'Brand_Reputation',
       'Price_net_zscore', 'Gquality_net_zscore', 'Goodsq_net_zscore',
       'Value_Driver_zscore', 'Cool_net_zscore', 'Innovative_net_zscore',
       'Exciting_net_zscore', 'SocResp_net_zscore', 'Brand_Driver_zscore',
       'Community_net_zscore', 'Friendly_net_zscore', 'PersonalRel_net_zscore',
       'Trustworthy_net_zscore', 'Relationship_Driver_zscore'],
      dtype='object')